# **Movie Review Platform Comparison**

## **Research Goal**

This project compares user-generated movie reviews from **IMDb and Letterboxd**.

The objective is to investigate whether **measurable linguistic features** such as review length, lexical diversity, and sentiment-related patterns differ across the two platforms.

### **Data Loading**

The project uses two publicly available datasets:

- IMDb Movie Reviews Dataset (50,000 reviews)
- Letterboxd Movie Reviews Dataset (90,016 reviews)

The datasets are loaded using pandas and will be used for exploratory text analysis.

In [5]:
import pandas as pd

In [6]:
imdb = pd.read_csv("../data/IMDB Dataset.csv")
letterboxd = pd.read_csv("../data/letterboxd_250movie_reviews.csv")

In [7]:
print(imdb.shape)
print(letterboxd.shape)

(50000, 2)
(90016, 6)

In [8]:
imdb.columns

Index(['review', 'sentiment'], dtype='str')

In [9]:
letterboxd.columns

Index(['Unnamed: 0', 'Review', 'Rating', 'Date', 'Status', 'Movie'], dtype='str')

In [10]:
imdb.head()

                                              review sentiment
0  One of the other reviewers has mentioned that ...  positive
1  A wonderful little production. <br /><br />The...  positive
2  I thought this was a wonderful way to spend ti...  positive
3  Basically there's a family where a little boy ...  negative
4  Petter Mattei's "Love in the Time of Money" is...  positive

In [11]:
letterboxd.head()

,Unnamed: 0,Review,Rating,Date,Status,Movie
0,0,I am an idiot. Why is it that I still dread wa...,★★★★★,01 Dec 2013,Watched,harakiri
1,1,honor in the individual is virtue honor in a s...,★★★★★,18 Jan 2022,NaN,harakiri
2,2,Brilliant. Riveting exploration of mortality a...,NaN,26 Jan 2024,Watched,harakiri
3,3,God damn what an impeccable film. Not dated in...,★★★★★,21 Jun 2021,Watched,harakiri
4,4,95First thing's first: giving a big thanks to ...,★★★★★,06 Sep 2020,Watched,harakiri